# Generated by Django 5.2.17 on 2026-10-03 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('camping', 'Camping'), ('perkakas', 'Perkakas'), ('fotografi', 'Fotografi'), ('fashion', 'Fashion'), ('buku', 'Buku'), ('olahraga', 'Olahraga & Outdoor'), ('game', 'Game'), ('travel', 'Travel'), ('elektronik', 'Elektronik'), ('hobi', 'Hobi'), ('otomotif', 'Otomotif'), ('aksesoris', 'Aksesoris'), ('Perlengkapan', 'Perlengkapan')], default='perlengkapan', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('baru', 'Baru'), ('baik', 'Baik'), ('cukup', 'Cukup Baik')], default='baik', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('dipinjam', 'Sedang Dipinjam'), ('tidak_tersedia', 'Tidak Tersedia')], default='tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.item')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
