# Generated by Django 5.2.17 on 2026-10-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('camping', 'Camping'), ('perkakas', 'Perkakas'), ('fotografi', 'Fotografi'), ('fashion', 'Fashion'), ('buku', 'Buku'), ('olahraga', 'Olahraga & Outdoor'), ('game', 'Game'), ('travel', 'Travel'), ('elektronik', 'Elektronik'), ('hobi', 'Hobi'), ('otomotif', 'Otomotif'), ('aksesoris', 'Aksesoris'), ('perlengkapan', 'Perlengkapan')], default='perlengkapan', max_length=50),
        ),
    ]
