# Generated by Django 5.2.17 on 2026-10-05 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_alter_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('menunggu_verifikasi', 'Menunggu Verifikasi'), ('menunggu_pembayaran', 'Menunggu Pembayaran'), ('menunggu_konfirmasi', 'Menunggu Konfirmasi'), ('ditolak', 'Ditolak'), ('disetujui', 'Disetujui'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu_verifikasi', max_length=30)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti/')),
                ('metode_pengambilan', models.CharField(choices=[('ambil_sendiri', 'Ambil Sendiri'), ('dikirim', 'Dikirim'), ('cod', 'COD / Ketemuan')], default='ambil_sendiri', max_length=20)),
                ('pesan_peminjam', models.TextField(blank=True, help_text='Pesan opsional buat pemilik')),
                ('catatan_penolakan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemberian', to=settings.AUTH_USER_MODEL)),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinjaman', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
